Add CRD functionality for coupons page
Note that even though the React component works, we cannot delete a coupon that is already associated with a restaurant due to foreign key constraints.

Error: Cannot delete or update a parent row: a foreign key constraint fails (`guic8igdw9aogppi`.`restaurants`, CONSTRAINT `restaurants_ibfk_1` FOREIGN KEY (`couponID`) REFERENCES `coupons` (`couponID`))